apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - name: html-container
          image: 506651622395.dkr.ecr.eu-west-2.amazonaws.com/password-ci-cd:latest
          ports:
            - containerPort: 80
